# Generated by Django 5.2.1 on 2025-06-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mover',
            old_name='vechicle',
            new_name='vehicle',
        ),
    ]
