# Generated by Django 5.2.1 on 2025-06-17 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mover', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideBookingRequestToMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[(0, 'Pending Request'), (1, 'Accepted'), (2, 'Confirmed'), (3, 'Reject'), (4, 'Expired')], max_length=1)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mover.mover')),
            ],
        ),
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('status', models.CharField(choices=[(0, 'Confirmed'), (1, 'Picked Up'), (2, 'Moving'), (3, 'Droped Off'), (4, 'Issue')], max_length=1)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('booking_request_mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ridebookingrequesttomover')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('vehicle_preferences', models.JSONField(default=dict)),
                ('eco_ride', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ride_searchings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehiclemake')),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehiclemodel')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehicletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ridebookingrequesttomover',
            name='ride_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ridesearch'),
        ),
    ]
