# Generated by Django 5.2.1 on 2025-06-30 14:50

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('parcel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the parcel in kg', max_digits=8)),
                ('recipient_contact', models.JSONField(default=dict)),
                ('is_scheduled_delivery', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('waiting', 'Waiting for Request Acceptance'), ('request_accepted', 'Delivery Request Accepted'), ('picked_up', 'Parcel Picked Up'), ('on_the_way', 'Parcel On the Way'), ('delivered', 'Parcel Delivered')], default='waiting', max_length=20)),
                ('special_instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('parcel_image', models.ImageField(blank=True, upload_to=core.utils.ImageUploadTo('parcel_image'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Parcel Type',
                'verbose_name_plural': 'Parcel Types',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pickedup', 'Picked Up'), ('moving', 'Moving'), ('dropedoff', 'Droped Off'), ('issue', 'Issue')], max_length=15)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequestToMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RideSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('vehicle_preferences', models.JSONField(default=dict)),
                ('eco_ride', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new_search', 'New Search'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='new_search', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
