# Generated by Django 5.2.1 on 2025-06-17 13:30

import core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('mover', '0002_vehicletype_bgcolor_vehicletype_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Parcel Type',
                'verbose_name_plural': 'Parcel Types',
            },
        ),
        migrations.AlterField(
            model_name='ridesearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('parcel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the parcel in kg', max_digits=8)),
                ('recipient_contact', models.JSONField(default=dict)),
                ('is_scheduled_delivery', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('waiting', 'Waiting for Request Acceptance'), ('request_accepted', 'Delivery Request Accepted'), ('picked_up', 'Parcel Picked Up'), ('on_the_way', 'Parcel On the Way'), ('delivered', 'Parcel Delivered')], default='waiting', max_length=20)),
                ('special_instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('parcel_image', models.ImageField(blank=True, upload_to=core.utils.VehicleImageUploadTo('image_1'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_deliveries', to=settings.AUTH_USER_MODEL)),
                ('parcel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.parceltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='RideBookingRequestToMover',
            new_name='RideRequestToMover',
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('booking_time', models.CharField(choices=[(0, 'Book Now'), (1, 'Book for Later')], default=0, max_length=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[(0, 'Single Ride'), (1, 'Reservation')], default=0, max_length=1)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day')], max_length=4, null=True)),
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, 'Confirmed'), (1, 'Picked Up'), (2, 'Moving'), (3, 'Droped Off'), (4, 'Issue')], max_length=1)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('booking_request_mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.riderequesttomover')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RideBooking',
        ),
    ]
