# Generated by Django 5.2.1 on 2025-07-03 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('customer', '0001_initial'),
        ('mover', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parceldelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='parcel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.parceltype'),
        ),
        migrations.AddField(
            model_name='riderequesttomover',
            name='mover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mover.mover'),
        ),
        migrations.AddField(
            model_name='ride',
            name='booking_request_mover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.riderequesttomover'),
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_searches', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='vehicle_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehiclemake'),
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mover.vehicletype'),
        ),
        migrations.AddField(
            model_name='riderequesttomover',
            name='ride_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ridesearch'),
        ),
        migrations.AlterUniqueTogether(
            name='riderequesttomover',
            unique_together={('ride_search', 'mover')},
        ),
    ]
