# Generated by Django 5.2.1 on 2025-07-06 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequesttomover',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequesttomover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
