# Generated by Django 5.2.1 on 2025-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldelivery',
            name='booking_time',
            field=models.CharField(choices=[('now', 'Book Now'), ('later', 'Book for Later')], default='now', max_length=10),
        ),
        migrations.AlterField(
            model_name='parceldelivery',
            name='booking_type',
            field=models.CharField(choices=[('single', 'Single Ride'), ('reservation', 'Reservation')], default='single', max_length=15),
        ),
        migrations.AlterField(
            model_name='ridesearch',
            name='booking_time',
            field=models.CharField(choices=[('now', 'Book Now'), ('later', 'Book for Later')], default='now', max_length=10),
        ),
        migrations.AlterField(
            model_name='ridesearch',
            name='booking_type',
            field=models.CharField(choices=[('single', 'Single Ride'), ('reservation', 'Reservation')], default='single', max_length=15),
        ),
    ]
