# Generated by Django 5.2.1 on 2025-06-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesearch',
            name='user',
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ride_searches', to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ridesearch',
            name='status',
            field=models.CharField(choices=[('new_search', 'New Search'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='new_search', max_length=15),
        ),
    ]
