# Generated by Django 5.2.1 on 2025-06-18 10:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_parceltype_alter_ridesearch_user_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ridesearch',
            name='status',
            field=models.CharField(choices=[('new_search', 'New Search'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parceldelivery',
            name='parcel_image',
            field=models.ImageField(blank=True, upload_to=core.utils.ImageUploadTo('parcel_image')),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pickedup', 'Picked Up'), ('moving', 'Moving'), ('dropedoff', 'Droped Off'), ('issue', 'Issue')], max_length=15),
        ),
        migrations.AlterField(
            model_name='riderequesttomover',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=15),
        ),
    ]
